# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3b2e141030178a81b1c8ac16b6292d8a96106793ff6effc374f2ca546774200bfc7e742a4afba008fb3b24afa432e7031100fd692da64e0d6bc1e1bf187e6d0

test:
  secret_key_base: 41aaac6bd1f0caa779aee40336f724d79c00cf4ea2d0b00f192b1808b2aa482a59b311a8d0ed53421fd06910f04ada50357b63682d01c8ff18d142f57d26c8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
